### ISSUE TITLE
Update for Kernel 4.11

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#118] opened 2017-05-25 16:19 UTC
I'm sure you already know, but 4.11.2 is out.

**Comment by fryfrog** [comment] 2017-05-26 15:56
Looks like a new stable release of OpenZFS is needed, according to https://aur.archlinux.org/packages/zfs-linux/

**Comment by philmmanjaro** [comment] 2017-06-08 12:20
Please check my [PKGBUILD](https://github.com/manjaro/packages-extra/blob/master/linux411-extramodules/spl_zfs/PKGBUILD) for which patches are needed to get it compiled for **v4.11** series.

**Comment by fafische** [comment] 2017-06-16 05:42
@demizer Do the devellopers of zfsonlinux know our updates are blocked for more than 3 weeks by now?
Can you try to speed things up, a little bit?

**Comment by philmmanjaro** [comment] 2017-06-16 07:33
The issue is more with this rather than with patches: https://github.com/zfsonlinux/spl/issues/620 Using **gcc6** it is fine.

**Comment by storrgie** [comment] 2017-06-16 13:00
@fafische be aware that there are issues upstream as @philmmanjaro alludes to. Squawk upstream if you're annoyed.

**Comment by demizer** [comment] 2017-06-16 18:32
@fafische you can install the archzfs-linux-git packages if you need to upgrade your kernel.

**Comment by alaricljs** [comment] 2017-06-21 02:10
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.10  Looks like what's needed has landed.

**Comment by demizer** [comment] 2017-06-21 17:47
@alaricljs I have released packages with that ZOL version. It does not fix the gcc 7.1 errors. That is scheduled for the next release: https://github.com/zfsonlinux/spl/projects/1#card-3418392

**Comment by alaricljs** [comment] 2017-06-21 18:04
@demizer ick, nice timing on that, missed the gcc issue.  When will the packages you released hit the archzfs.com/archzfs repo?  I'll gladly roll back gcc :)

**Comment by demizer** [comment] 2017-06-21 18:17
@alaricljs you can install the archzfs-linux-git packages if you want to update your kernel. Personally, I am holding of updating my kernel until I can update the archzfs-linux packages because I don't need anything from 4.11. 

I don't want to require gcc 6.3 because that will break the install unless gcc 6.3 has been explicitly installed.

**Comment by storrgie** [comment] 2017-06-21 19:39
@demizer when the prompt comes through when trying to `-Syu`, if you hit `y` does it just update the other packages? I don't proceed for fear that it would update the kernel itself and then I'd be unable to use ZFS.

**Comment by philmmanjaro** [comment] 2017-06-21 19:49
Simply add https://github.com/zfsonlinux/spl/commit/4f8e643afe9d8cc558566e1dda05ef597cb2526e as patch and it compiles fine with **gcc 7.1.1** ...

**Comment by demizer** [comment] 2017-06-21 23:08
@storrgie you can use `--ignore linux` to ignore the kernel package. Otherwise pacman will exit early because it cannot satisfy the kernel dependency for archzfs.

**Comment by saghm** [comment] 2017-06-25 18:43
You can also add `linux` to `IgnorePkg` line in your /etc/pacman.conf (uncomment if needed) and then just continue updating as normal, which is what I've been doing while waiting.

**Closed** 2017-07-14 17:30 UTC
Labels: upstream-fix-needed

**Comment by saghm** [comment] 2017-07-17 03:08
Will the packages hosted at demizerone.com be updated?

**Comment by fryfrog** [comment] 2017-07-17 16:09
Comments imply we won't get packages until this compiles with gcc 7.1, so should this issue maybe stay open?

**Comment by minextu** [comment] 2017-07-17 16:34
It does compile again, that's why this issue has been closed. @demizer is currently testing all recent changes, as far as I know.

**Comment by fryfrog** [comment] 2017-07-18 00:10
Ah, cool! :)

**Comment by fryfrog** [comment] 2017-07-27 05:00
This never did actually get resolved and now 0.7.0 is here. Maybe next time keep the issue open so it is easier to surface by others?
