### ISSUE TITLE
Serious upstream issue with zfsonlinux 0.7.7

### ISSUE THREAD

**Issue by kode54** [archzfs/archzfs#241] opened 2018-04-09 21:58 UTC
https://github.com/zfsonlinux/zfs/issues/7401

Basically, copying a directory of thousands of small files, one or two will randomly fail, and then the rest of the directory will be invisible except if you know the exact name of the affected file(s). Introduced by a commit between 0.7.6 and 0.7.7.

The commit has already been isolated and reverted post-0.7.7. A fix which does what the original commit did, without the horrible race condition, is hopefully in the works.

I'm not sure that it affects 4.x kernels, though.

**Comment by demizer** [comment] 2018-04-09 22:15
> The 0.7.7 release has been removed from the CentOS and Fedora RPM repositories.

I am perfectly willing to roll back to 0.7.6. How does everyone feel about this? I personally have not seen any issues on my machine, but then again I don't have thousands of small files in any one directory.

**Comment by UweSauter** [comment] 2018-04-09 22:56
As reported in the original issue (zfsonlinux/zfs#7401) Arch is affected. I have following versions installed and can reproduce with @trisk's script (https://gist.github.com/trisk/9966159914d9d5cd5772e44885112d30)
```
local/spl-linux-git 2018.04.04.r1070.581bc01.4.15.15.1-1 (archzfs-linux-git)
local/spl-utils-common-git 2018.04.04.r1070.581bc01-1 (archzfs-linux-git)
local/zfs-linux-git 2018.04.04.r3402.533ea0415.4.15.15.1-1 (archzfs-linux-git)
local/zfs-utils-common-git 2018.04.04.r3402.533ea0415-1 (archzfs-linux-git)
```

**Comment by NoSuck** [comment] 2018-04-09 22:59
> I am perfectly willing to roll back to 0.7.6. How does everyone feel about this?
I would be fine with this, as that's what I was planning to do regardless (if 0.7.8 isn't released in the next day or two).  Upstream seems to be taking the issue seriously, so I doubt the release will be delayed.

**Comment by bjin** [comment] 2018-04-10 03:53
0.7.8 is already released, see https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.8

**Closed** 2018-04-10 08:00 UTC
Labels: C-bug, E-medium, P-high
