### ISSUE TITLE
Invalid or corrupted database (PGP signature) when updating through powerpill or yay

### ISSUE THREAD

**Issue by sotiris-bos** [archzfs/archzfs#342] opened 2020-06-09 20:36 UTC
Hello.

I am getting this error when I am trying to update my system either through powerpill or yay. I do not get the error when updating through pacman.

Any idea what might be the cause and the fix?

Edit: powerpill output:

````

Status Legend:
(OK):download completed.
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is invalid
error: database 'archzfs' is not valid (invalid or corrupted database (PGP signature))

````

**Comment by sotiris-bos** [comment] 2020-06-15 14:24
I do have added the key. My SigLevel is 
```
SigLevel    = PackageRequired
```

**Comment by thiderman** [comment] 2020-06-15 16:38
I'm having what's probably a related problem:

```
thiderman@silverwing /etc $ sudo pacman-key -r F75D9D76                                                                     
gpg: keyserver receive failed: Server indicated a failure
==> ERROR: Remote key not fetched correctly from keyserver.

thiderman@silverwing /etc $ sudo pacman-key --lsign-key F75D9D76
gpg: key F26D363E525576DE was created 20016 seconds in the future (time warp or clock problem)
  -> Locally signing key F75D9D76...
==> ERROR: F75D9D76 could not be locally signed.

thiderman@silverwing /etc $ date
Mon 15 Jun 2020 06:16:46 PM CEST 

thiderman@silverwing /etc $ gpg --debug 1024 --keyserver hkp://pgp.mit.edu:11371 --search-keys F75D9D76
gpg: Note: no default option file '/home/thiderman/.gnupg/gpg.conf'
gpg: enabled debug flags: ipc
gpg: DBG: chan_3 <- # Home: /home/thiderman/.gnupg
gpg: DBG: chan_3 <- # Config: [none]
gpg: DBG: chan_3 <- OK Dirmngr 2.2.20 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.2.20
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KEYSERVER --clear hkp://pgp.mit.edu:11371
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_SEARCH -- F75D9D76
gpg: DBG: chan_3 <- ERR 167772379 Server indicated a failure <Dirmngr>
gpg: error searching keyserver: Server indicated a failure
gpg: keyserver search failed: Server indicated a failure
gpg: DBG: chan_3 -> BYE
gpg: secmem usage: 0/32768 bytes in 0 blocks
```

Can't seem to download the key. My date is correct, so no idea where the "20000 seconds in the future" comes from.

**Comment by Nalorokk** [comment] 2020-06-16 00:14
Right now have similliar problems, as @thiderman described

**Comment by thiderman** [comment] 2020-06-16 09:19
I've temporarily worked around this by setting `SigLevel = Never` on the `[archzfs]` repository. Not the solution I'd like, but at least I can continue working. :woman_shrugging:

**Comment by thiderman** [comment] 2020-06-17 13:16
Perhaps it's related to the [SKS keyservers under attack](https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f) document? It's a year ago, but it seems like the symptoms are either the same or very similar?

**Comment by jmesmon** [comment] 2020-07-08 22:53
I'm also observing this issue. https://github.com/archzfs/archzfs/issues/346 appears to reference it.

I resolved by using `pacman-key --edit-key F75D9D76` and using `trust` `4` to fully trust the key. After this the gpg verification passes.

**Comment by drbawb** [comment] 2020-07-09 13:46
I was getting a similar error this morning: `error: archzfs-testing: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust` on a machine that's previously trusted this repo just fine.

I tried retrieving the key again w/ `pacman-key -r` and `pacman-key --lsign-key` and couldn't resolve the issue.

 What worked for me was following the instructions to manually install the key linked by the wiki:

```
# wget  https://archzfs.com/archzfs.gpg
# pacman-key -a archzfs.gpg
```

**Comment by dmp1ce** [comment] 2020-07-09 14:31
@jmesmon Do you know why the key wasn't already trusted?

**Comment by caleb** [comment] 2020-07-09 14:59
I tried running:

```
sudo pacman-key -r F75D9D76
gpg: keyserver receive failed: No data
==> ERROR: Remote key not fetched correctly from keyserver.
```

But when I used @drbawb's method it worked correctly, thanks!

Anybody know why there would be an error fetching the key? I've had this install for over a year with Archzfs, so I don't know what's changed.

**Comment by rhavenn** [comment] 2020-07-09 17:36
It seems the downloaded key (https://archzfs.com/archzfs.gpg) has an extra sig in it.

pacman-key --list-sigs output before the manual input:

`
pub   rsa2048 2018-07-09 [SC] [expires: 2023-02-03]
      DDF7DB817396A49B2A2723F7403BD972F75D9D76
uid           [ unknown] ArchZFS Bot <buildbot@archzfs.com>
sig 3        403BD972F75D9D76 2018-07-17  ArchZFS Bot <buildbot@archzfs.com>
sig   L      EEF32CC30FDF4E9B 2019-04-21  Pacman Keyring Master Key <pacman@localhost>
sig 3        403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
uid           [ unknown] ArchZFS Bot <bot@archzfs.com>
sig 3        403BD972F75D9D76 2018-07-09  ArchZFS Bot <buildbot@archzfs.com>
sig   L      EEF32CC30FDF4E9B 2019-04-21  Pacman Keyring Master Key <pacman@localhost>
sig 3        403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
sub   rsa2048 2018-07-09 [E] [expires: 2023-02-03]
sig          403BD972F75D9D76 2018-07-09  ArchZFS Bot <buildbot@archzfs.com>
sig          403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
`

pacman-key --list-sigs output after the manual input:
`
pub   rsa2048 2018-07-09 [SC] [expires: 2023-02-03]
      DDF7DB817396A49B2A2723F7403BD972F75D9D76
uid           [  full  ] ArchZFS Bot <buildbot@archzfs.com>
sig 3        403BD972F75D9D76 2018-07-17  ArchZFS Bot <buildbot@archzfs.com>
sig   L      EEF32CC30FDF4E9B 2019-04-21  Pacman Keyring Master Key <pacman@localhost>
sig 3        403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
sig          22C69579E1123CE6 2019-05-27  [User ID not found]
uid           [  full  ] ArchZFS Bot <bot@archzfs.com>
sig 3        403BD972F75D9D76 2018-07-09  ArchZFS Bot <buildbot@archzfs.com>
sig   L      EEF32CC30FDF4E9B 2019-04-21  Pacman Keyring Master Key <pacman@localhost>
sig 3        403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
sig          22C69579E1123CE6 2019-05-27  [User ID not found]
sub   rsa2048 2018-07-09 [E] [expires: 2023-02-03]
sig          403BD972F75D9D76 2018-07-09  ArchZFS Bot <buildbot@archzfs.com>
sig          403BD972F75D9D76 2020-02-04  ArchZFS Bot <buildbot@archzfs.com>
`

**Comment by joe-average-user** [comment] 2020-07-10 09:00
I can confirm this issue happens on all my arch installations with zfs. pacman refuses to do anything because of this. Is this a hack?

**Comment by drbawb** [comment] 2020-07-10 13:46
The key present on [Ubuntu's keyserver](https://keyserver.ubuntu.com/pks/lookup?search=0xDDF7DB817396A49B2A2723F7403BD972F75D9D76&fingerprint=on&op=index) also shows that extra signature (` 22c69579e1123ce6`) that's present in the copy of the key downloaded manually.

**Comment by mikedilger** [comment] 2020-07-10 23:28
Even with all of the above advice, and issue #346, I still can't upgrade:

    error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
    error: failed to update archzfs (invalid or corrupted database (PGP signature))

I think I've got only the good key imported and signed.

    $ sudo pacman-key --finger F75D9D7
    pub   rsa2048 2018-07-09 [SC] [expires: 2023-02-03]
          DDF7 DB81 7396 A49B 2A27  23F7 403B D972 F75D 9D76
    uid           [ unknown] ArchZFS Bot <buildbot@archzfs.com>
    uid           [ unknown] ArchZFS Bot <bot@archzfs.com>
    sub   rsa2048 2018-07-09 [E] [expires: 2023-02-03]

I've deleted /var/lib/pacman/sync/archzfs.* and it makes no difference.

But when I use gpg, import the above key into my regular gpg keystore, and verify that archzfs.db is signed by archzfs.db.sig, it seems that the verification works (I didn't trust it in my regular gpg keystore, but that's neither here nor there).

    $ gpg --verify archzfs.db.sig  archzfs.db
    gpg: Signature made Sat 04 Jul 2020 06:21:41 PM NZST
    gpg:                using RSA key DDF7DB817396A49B2A2723F7403BD972F75D9D76
    gpg: Good signature from "ArchZFS Bot <buildbot@archzfs.com>" [unknown]
    gpg:                 aka "ArchZFS Bot <bot@archzfs.com>" [unknown]
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: DDF7 DB81 7396 A49B 2A27  23F7 403B D972 F75D 9D76

**Comment by rhavenn** [comment] 2020-07-10 23:34
Delete from the pacman key database and re-importing using the long key worked for me.
`sudo pacman-key -d DDF7DB817396A49B2A2723F7403BD972F75D9D76`
and then
```
sudo pacman-key -r DDF7DB817396A49B2A2723F7403BD972F75D9D76
sudo pacman-key --lsign-key DDF7DB817396A49B2A2723F7403BD972F75D9D76
```

**Comment by mikedilger** [comment] 2020-07-10 23:39
Thanks @rhavenn that works for me too.

**Comment by stevleibelt** [comment] 2020-07-13 11:48
@rhavenn thank you very much, this helped me out.

@minextu any idea how this has happend?

**Comment by jmesmon** [comment] 2020-07-13 15:37
@dmp1ce 
> @jmesmon Do you know why the key wasn't already trusted?

I don't. I suspect it might have to do with the key expiring (prehaps causing the initial trust to be removed?) and that not being re-trusted automatically after the refresh un-expires the key.

**Comment by MikeVensel** [comment] 2020-07-17 16:24
I also had this issue. Thanks to @rhavenn for the solution. I'm newer to Arch and haven't had this issue occur before so is this something I should be concerned about?

**Comment by minextu** [comment] 2020-07-17 17:56
It's most likely because I extended the expiration date of the key. On my machine I was able to just receive the updated key with `pacman-key -r DDF7DB817396A49B2A2723F7403BD972F75D9D76` and I didn't need to sign it again.

**Closed by minextu** 2020-07-17 17:56 UTC
Labels: C-question

**Comment by btwe** [comment] 2022-09-14 19:33
I came here because I have similar a problem and another solution.

I use pikaur to sync/update my system. I cannot reproduce this, but once in while during the process `pikaur -Suy == pacman -Suy` the keyring seems to be corrupted; this feels quite strange I have to say. The update process fails while upgrading package from archzfs and then pacman cannot work anymore because of the corrupted keyring:

```
% pikaur -Suy
[…]
NOTE: GnuPG's systemd sockets are now enabled in the vendor location /usr/lib/systemd/user/!
[…]
==> Appending keys from archlinux.gpg...
==> Disabling revoked keys in keyring...
  -> Disabled 1 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: [don't know]: invalid packet (ctb=00)
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keydb_get_keyblock failed: Invalid keyring
gpg: validate_key_list failed
==> ERROR: Trust database could not be updated.
==> Updating trust database...
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
[… message is repeated many times …]
error: archzfs: signature from "DDF7DB817396A49B2A2723F7403BD972F75D9D76" is unknown trust
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keyring_get_keyblock failed: Invalid keyring
gpg: failed to rebuild keyring cache: Invalid keyring
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: [don't know]: invalid packet (ctb=00)
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keydb_get_keyblock failed: Invalid keyring
gpg: validate_key_list failed
==> ERROR: Trust database could not be updated.
error: command failed to execute correctly
[…]
```
The keyring seems to corrupt:
```
% sudo pacman-key -l
gpg: checking the trustdb
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
[… message is repeated many times …]
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keyring_get_keyblock failed: Invalid keyring
gpg: failed to rebuild keyring cache: Invalid keyring
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: [don't know]: invalid packet (ctb=00)
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keydb_get_keyblock failed: Invalid keyring
gpg: validate_key_list failed
/etc/pacman.d/gnupg/pubring.gpg
[… keys are listed ...]
```

From here I am not able to import any keys. Or re-set the trust of the archzfs key. My way to fix this radical. Get a fresh new keyring and add the archzfs key again (be aware to also re-add other keys if needed)
```
% sudo rm -rf /etc/pacman.d/gnupg
% sudo pacman-key --init
% sudo pacman-key --populate archlinux
% sudo pacman-key --add archzfs.key # key files downloaded from archzfs github before
% sudo pacman-key --lsign-key DDF7DB817396A49B2A2723F7403BD972F75D9D76
```
