### ISSUE TITLE
Cant Switch zfs Versions Due to Dependencies

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#70] opened 2016-09-05 20:52 UTC
Do we have any way of finding out how long it will be?

When attempting to switch to zfs-linux-git from zfs-linux I get errors related to linux not being able to upgrade due to dependencies.

```
resolving dependencies...
warning: ignoring package linux-4.7.2-1
warning: cannot resolve "linux=4.7.2", a dependency of "spl-linux-git"
warning: cannot resolve "spl-linux-git", a dependency of "zfs-linux-git"
warning: ignoring package linux-4.7.2-1
warning: cannot resolve "linux=4.7.2", a dependency of "spl-linux-git"
warning: cannot resolve "spl-linux-git", a dependency of "zfs-utils-linux-git"
warning: ignoring package linux-4.7.2-1
warning: cannot resolve "linux=4.7.2", a dependency of "zfs-utils-linux-git"
warning: cannot resolve "zfs-utils-linux-git", a dependency of "zfs-linux-git"
warning: ignoring package linux-4.7.2-1
warning: cannot resolve "linux=4.7.2", a dependency of "zfs-linux-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-linux-git
```

_Posted at demizer's [request](https://github.com/archzfs/archzfs/issues/63#issuecomment-244792037)._

**Comment by chrissnell** [comment] 2016-09-08 03:16
+1

**Comment by Sweyn78** [comment] 2016-09-11 22:40
+1
I can't go from the git version to the normal version.

**Comment by demizer** [comment] 2016-09-13 07:44
Duplicate of #58

**Closed by demizer** 2016-09-13 07:44 UTC
Labels: bug
