### ISSUE TITLE
zfs-utils-git=2023.01.13.r8335.gd27c7ba62f doesn't exist

### ISSUE THREAD

**Issue by frebib** [archzfs/archzfs#475] opened 2023-01-17 22:50 UTC
```
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 testing is up to date
 multilib is up to date
 archzfs is up to date
:: Starting full system upgrade...
resolving dependencies...
warning: cannot resolve "zfs-utils-git=2023.01.13.r8335.gd27c7ba62f", a dependency of "zfs-dkms-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-dkms-git

:: Do you want to skip the above package for this upgrade? [y/N] y
```

Looks like the file is indeed missing https://archzfs.com/archzfs/x86_64/

**Comment by minextu** [comment] 2023-01-26 00:47
It's caused by debug packages being build by default now in the new devtools release. It will require changes to `repo.sh` to detect these debug packages and add them alongside the regular zfs-utils ones. Right now only the newest build package is being added.

I will try to get around fixing this by the weekend hopefully. Sorry for the blocking update this is causing

**Comment by YaroKasear** [comment] 2023-01-27 16:10
> Any chance of getting this fixed any time soon? I'm also affected, switched to git on the advice of reddit when Arch updated to a version of the kernel that release OpenZFS doesn't support yet. Can't switch back because apparently git has some newer features that is not available on the release version of OpenZFS.



> Any chance of getting this fixed any time soon? I'm also affected, switched to git on the advice of reddit when Arch updated to a version of the kernel that release OpenZFS doesn't support yet. Can't switch back because apparently git has some newer features that is not available on the release version of OpenZFS.

Not that this is entirely relevant to the issue, but this is why I recommend the DKMS packages, so I don't have to care if there's a build for my given kernel. I wound up using git for a feature I no longer use at a time when it wasn't in stable (Encryption.)

**Comment by RAMChYLD** [comment] 2023-01-27 16:15
Well, the problem is, Arch upgraded to a kernel that then ZFS release did not like. I do use the DKMS package. The ZFS modules refused to compile allegedly because the kernel is too new and the configure script halted saying that the kernel is unsupported because it's too new.

**Comment by seonwoolee** [comment] 2023-01-27 20:05
> Not that this is entirely relevant to the issue, but this is why I recommend the DKMS packages, so I don't have to care if there's a build for my given kernel. I wound up using git for a feature I no longer use at a time when it wasn't in stable (Encryption.)

DKMS merely means that there is a process to _attempt_ compilation of the kernel modules against the latest kernel installed on your system. It **does not** mean that compilation will succeed, or that even if the compilation succeeds, that the module behaves as intended. 

For example, there is a bug in ZFS 2.1.7 with opening (for example) "/tmp" with O_TMPFILE flags on a system with the "/tmp" directory located on ZFS on the 6.1 kernel, but not the 5.15.83 or 5.19 kernels. Even if DKMS let you compile ZFS against the 6.1 kernel, it will not work as intended

**Comment by seonwoolee** [comment] 2023-01-31 01:04
Yes, I know. That's my point. I gave that example to explain how you do not want to upgrade to 6.1 on ZFS 2.1.7 even if you're using DKMS, which is what @YaroKasear was saying you can do

**Comment by joe-average-user** [comment] 2023-02-02 10:45
I guess this is pretty much the same problem, not?

# pacman -S zfs-linux-lts-git
Abhängigkeiten werden aufgelöst …
Warnung: Kann "zfs-utils-git=2023.01.17.r8343.ga379083d9f" nicht auflösen (eine Abhängigkeit von "zfs-linux-lts-git")
Warnung: Kann "linux-lts=5.15.88-2" nicht auflösen (eine Abhängigkeit von "zfs-linux-lts-git")
:: Das folgende Paket kann aufgrund nicht auflösbarer Abhängigkeiten nicht aktualisiert werden:
      zfs-linux-lts-git

:: Möchten Sie das oben genannte Paket bei dieser Aktualisierung überspringen? [j/N]

**Comment by stevleibelt** [comment] 2023-02-02 20:38
@seonwoolee I try to reproduce this issue.

I've build an [archios with dkms zfs](https://archzfs.leibelt.de) and all is working fine.

uname -a: 6.1.9-arch1-1
zfs --version: zfs-2.1.7-1, zfs-kmod-2.7.1-1

What do I miss?

**Comment by YaroKasear** [comment] 2023-02-03 16:21
Is there any progress on a fix for this? It's been blocking updates for quite a while now.

**Closed** 2023-02-03 19:49 UTC
Labels: C-bug

**Comment by minextu** [comment] 2023-02-03 19:55
Sorry didn't have a ton of time recently, new packages should go out soon

**Comment by joe-average-user** [comment] 2023-02-04 11:11
Hm, sorry but that still does not work:
pacman -Syu
:: Paketdatenbanken werden synchronisiert …
 core ist aktuell
 extra ist aktuell
 community ist aktuell
 archzfs ist aktuell
:: Vollständige Systemaktualisierung wird gestartet …
Abhängigkeiten werden aufgelöst …
Warnung: Kann "zfs-utils-git=2023.01.17.r8343.ga379083d9f" nicht auflösen (eine Abhängigkeit von "zfs-linux-lts-git")
Warnung: Kann "linux-lts=5.15.88-2" nicht auflösen (eine Abhängigkeit von "zfs-linux-lts-git")
:: Das folgende Paket kann aufgrund nicht auflösbarer Abhängigkeiten nicht aktualisiert werden:
      zfs-linux-lts-git

:: Möchten Sie das oben genannte Paket bei dieser Aktualisierung überspringen? [j/N] 
Fehler: Vorgang konnte nicht vorbereitet werden (Kann Abhängigkeiten nicht erfüllen)
:: Unerfüllbare Abhängigkeit »zfs-utils-git=2023.01.17.r8343.ga379083d9f«, benötigt von zfs-linux-lts-git
:: Unerfüllbare Abhängigkeit »linux-lts=5.15.88-2«, benötigt von zfs-linux-lts-git


How to proceed and get the archzfs updates again?

**Comment by minextu** [comment] 2023-02-04 15:02
sounds like you might be using an outdated mirror, try using a different one or the official one:
```
[archzfs]
Server = https://archzfs.com/$repo/$arch
```

**Comment by joe-average-user** [comment] 2023-02-05 10:06
Hm, unfortunately I am already using this:

[archzfs]
Server = http://archzfs.com/$repo/$arch

Is there are difference between http and https ?
