### ISSUE TITLE
requires linux=4.2.1-1

### ISSUE THREAD

**Issue by tristan-k** [archzfs/archzfs#46] opened 2015-10-10 12:57 UTC
I cant update my system anymore.

    $ uname -a
    Linux pb4540s 4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux
    $ pacman -Syu
    :: Starting full system upgrade...
    resolving dependencies...
    looking for conflicting packages...
    error: failed to prepare transaction (could not satisfy dependencies)
    :: spl-git: requires linux=4.2.1-1
    :: zfs-git: requires linux=4.2.1-1

**Comment by Finkregh** [comment] 2016-03-14 16:26
sorta-dup of https://github.com/archzfs/archzfs/issues/28

**Comment by demizer** [comment] 2016-04-17 21:21
Dupe of #28

**Closed by demizer** 2016-04-17 21:21 UTC
